
mqtt:
  enabled: False

detectors:
  ov:
    type: openvino
    device: CPU
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras: {}  # No cameras defined, UI wizard should be used
version: 0.18-0
